### ISSUE TITLE
清华镜像失效

### ISSUE THREAD

**Issue by Crownor** [weixiao-huang/silver-spoon#1]
在 config.list 文件中的清华镜像全部失效，eg：
`Ign:1 https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial main InRelease`

**Comment by weixiao-huang** [comment]
我这里是没问题的，尝试清掉缓存重新 build 一下镜像试试：
```
docker build -t ucore . --no-cache
```
如果不行的话，可以给个复现 bug 的步骤

**Comment by Crownor** [comment]
我把复现发你邮件了，麻烦了0.0

**Comment by weixiao-huang** [comment]
你好，我这边无法复现你的问题，我现在更新了一下版本库，你重新 pull 一下，看看有没有改善，如果没有的话，请尝试把 `Dockerfile` 里的 `mirrors.tuna.tsinghua.edu.cn` 换成其他的源试试，具体有哪些推荐的源我在新的 `Dockerfile` 里写了注释

**Comment by Crownor** [comment]
ok 啦，多谢
