### ISSUE TITLE
执行make init 报错

### ISSUE THREAD

**Issue by roothoo2** [weixiao-huang/silver-spoon#2]
错误如下:
Step 5/7 : RUN wget -P /root git.io/.gdbinit
 ---> Running in 2ceef4da54ff
--2019-06-12 13:20:55--  http://git.io/.gdbinit
Resolving git.io (git.io)... 3.214.163.243, 52.73.9.93, 52.207.111.186, ...
Connecting to git.io (git.io)|3.214.163.243|:80... connected.
HTTP request sent, awaiting response... No data received.
Retrying.
`````````````````````````````````````
The command '/bin/sh -c wget -P /root git.io/.gdbinit' returned a non-zero code: 4
make: *** [build] Error 4

**Comment by roothoo2** [comment]
已经解决了，在工程新建config/.gdbinit文件，把https://github.com/weixiao-huang/silver-spoon/blob/3ab3aa3256224452a710f3353a4c8ab47e9544bf/config/.gdbinit  的内容全部copy下来。
删除Dockerfile这行'/bin/sh -c wget -P /root git.io/.gdbinit'就ok了

**Comment by weixiao-huang** [comment]
估计是被墙了，或者是你的本机不太通外网
